# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modelOrderReduction.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(762, 645)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.form = QtGui.QTabWidget(self.centralwidget)
        self.form.setObjectName(_fromUtf8("form"))
        self.MainParameters = QtGui.QWidget()
        self.MainParameters.setObjectName(_fromUtf8("MainParameters"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.MainParameters)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_path = QtGui.QLabel(self.MainParameters)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_path.setFont(font)
        self.label_path.setObjectName(_fromUtf8("label_path"))
        self.verticalLayout_3.addWidget(self.label_path)
        self.layout_path = QtGui.QGridLayout()
        self.layout_path.setObjectName(_fromUtf8("layout_path"))
        self.btn_scene = QtGui.QPushButton(self.MainParameters)
        self.btn_scene.setObjectName(_fromUtf8("btn_scene"))
        self.layout_path.addWidget(self.btn_scene, 0, 0, 1, 1)
        self.lineEdit_mesh = QtGui.QTextEdit(self.MainParameters)
        self.lineEdit_mesh.setTabChangesFocus(False)
        self.lineEdit_mesh.setReadOnly(True)
        self.lineEdit_mesh.setObjectName(_fromUtf8("lineEdit_mesh"))
        self.layout_path.addWidget(self.lineEdit_mesh, 1, 1, 1, 1)
        self.btn_mesh = QtGui.QPushButton(self.MainParameters)
        self.btn_mesh.setObjectName(_fromUtf8("btn_mesh"))
        self.layout_path.addWidget(self.btn_mesh, 1, 0, 1, 1)
        self.btn_output = QtGui.QPushButton(self.MainParameters)
        self.btn_output.setObjectName(_fromUtf8("btn_output"))
        self.layout_path.addWidget(self.btn_output, 2, 0, 1, 1)
        self.lineEdit_output = QtGui.QLineEdit(self.MainParameters)
        self.lineEdit_output.setReadOnly(True)
        self.lineEdit_output.setObjectName(_fromUtf8("lineEdit_output"))
        self.layout_path.addWidget(self.lineEdit_output, 2, 1, 1, 1)
        self.lineEdit_scene = QtGui.QLineEdit(self.MainParameters)
        self.lineEdit_scene.setReadOnly(True)
        self.lineEdit_scene.setObjectName(_fromUtf8("lineEdit_scene"))
        self.layout_path.addWidget(self.lineEdit_scene, 0, 1, 1, 1)
        self.checkBox_mesh = QtGui.QCheckBox(self.MainParameters)
        self.checkBox_mesh.setText(_fromUtf8(""))
        self.checkBox_mesh.setChecked(False)
        self.checkBox_mesh.setObjectName(_fromUtf8("checkBox_mesh"))
        self.layout_path.addWidget(self.checkBox_mesh, 1, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.layout_path)
        self.label_reductionParam = QtGui.QLabel(self.MainParameters)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_reductionParam.setFont(font)
        self.label_reductionParam.setTextFormat(QtCore.Qt.AutoText)
        self.label_reductionParam.setScaledContents(False)
        self.label_reductionParam.setObjectName(_fromUtf8("label_reductionParam"))
        self.verticalLayout_3.addWidget(self.label_reductionParam)
        self.layout_reductionParam = QtGui.QGridLayout()
        self.layout_reductionParam.setObjectName(_fromUtf8("layout_reductionParam"))
        self.checkBox_AddTranslation = QtGui.QCheckBox(self.MainParameters)
        self.checkBox_AddTranslation.setText(_fromUtf8(""))
        self.checkBox_AddTranslation.setObjectName(_fromUtf8("checkBox_AddTranslation"))
        self.layout_reductionParam.addWidget(self.checkBox_AddTranslation, 4, 1, 1, 1)
        self.label_NodeToReduce = QtGui.QLabel(self.MainParameters)
        self.label_NodeToReduce.setObjectName(_fromUtf8("label_NodeToReduce"))
        self.layout_reductionParam.addWidget(self.label_NodeToReduce, 1, 0, 1, 1)
        self.label_AddTranslation = QtGui.QLabel(self.MainParameters)
        self.label_AddTranslation.setObjectName(_fromUtf8("label_AddTranslation"))
        self.layout_reductionParam.addWidget(self.label_AddTranslation, 4, 0, 1, 1)
        self.label_moduleName = QtGui.QLabel(self.MainParameters)
        self.label_moduleName.setObjectName(_fromUtf8("label_moduleName"))
        self.layout_reductionParam.addWidget(self.label_moduleName, 0, 0, 1, 1)
        self.lineEdit_NodeToReduce = QtGui.QLineEdit(self.MainParameters)
        self.lineEdit_NodeToReduce.setObjectName(_fromUtf8("lineEdit_NodeToReduce"))
        self.layout_reductionParam.addWidget(self.lineEdit_NodeToReduce, 1, 1, 1, 1)
        self.lineEdit_moduleName = QtGui.QLineEdit(self.MainParameters)
        self.lineEdit_moduleName.setText(_fromUtf8(""))
        self.lineEdit_moduleName.setObjectName(_fromUtf8("lineEdit_moduleName"))
        self.layout_reductionParam.addWidget(self.lineEdit_moduleName, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.layout_reductionParam)
        self.lanel_animationParam = QtGui.QLabel(self.MainParameters)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.lanel_animationParam.setFont(font)
        self.lanel_animationParam.setObjectName(_fromUtf8("lanel_animationParam"))
        self.verticalLayout_3.addWidget(self.lanel_animationParam)
        self.tableWidget_animationParam = QtGui.QTableWidget(self.MainParameters)
        self.tableWidget_animationParam.setObjectName(_fromUtf8("tableWidget_animationParam"))
        self.tableWidget_animationParam.setColumnCount(4)
        self.tableWidget_animationParam.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_animationParam.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_animationParam.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_animationParam.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_animationParam.setHorizontalHeaderItem(3, item)
        self.verticalLayout_3.addWidget(self.tableWidget_animationParam)
        self.layout_animationParam = QtGui.QGridLayout()
        self.layout_animationParam.setObjectName(_fromUtf8("layout_animationParam"))
        self.btn_addLine = QtGui.QPushButton(self.MainParameters)
        self.btn_addLine.setObjectName(_fromUtf8("btn_addLine"))
        self.layout_animationParam.addWidget(self.btn_addLine, 0, 1, 1, 2)
        self.btn_removeLine = QtGui.QPushButton(self.MainParameters)
        self.btn_removeLine.setObjectName(_fromUtf8("btn_removeLine"))
        self.layout_animationParam.addWidget(self.btn_removeLine, 0, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_animationParam.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.layout_animationParam)
        self.form.addTab(self.MainParameters, _fromUtf8(""))
        self.AdvancedSettings = QtGui.QWidget()
        self.AdvancedSettings.setObjectName(_fromUtf8("AdvancedSettings"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.AdvancedSettings)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.layout_advancedSettings = QtGui.QGridLayout()
        self.layout_advancedSettings.setObjectName(_fromUtf8("layout_advancedSettings"))
        self.checkBox_verbose = QtGui.QCheckBox(self.AdvancedSettings)
        self.checkBox_verbose.setText(_fromUtf8(""))
        self.checkBox_verbose.setObjectName(_fromUtf8("checkBox_verbose"))
        self.layout_advancedSettings.addWidget(self.checkBox_verbose, 0, 1, 1, 1)
        self.label_toKeep = QtGui.QLabel(self.AdvancedSettings)
        self.label_toKeep.setObjectName(_fromUtf8("label_toKeep"))
        self.layout_advancedSettings.addWidget(self.label_toKeep, 6, 0, 1, 1)
        self.lineEdit_toKeep = QtGui.QLineEdit(self.AdvancedSettings)
        self.lineEdit_toKeep.setObjectName(_fromUtf8("lineEdit_toKeep"))
        self.layout_advancedSettings.addWidget(self.lineEdit_toKeep, 6, 1, 1, 1)
        self.label_verbose = QtGui.QLabel(self.AdvancedSettings)
        self.label_verbose.setObjectName(_fromUtf8("label_verbose"))
        self.layout_advancedSettings.addWidget(self.label_verbose, 0, 0, 1, 1)
        self.lineEdit_tolModes = QtGui.QLineEdit(self.AdvancedSettings)
        self.lineEdit_tolModes.setText(_fromUtf8(""))
        self.lineEdit_tolModes.setObjectName(_fromUtf8("lineEdit_tolModes"))
        self.layout_advancedSettings.addWidget(self.lineEdit_tolModes, 4, 1, 1, 1)
        self.checkBox_addToLib = QtGui.QCheckBox(self.AdvancedSettings)
        self.checkBox_addToLib.setText(_fromUtf8(""))
        self.checkBox_addToLib.setObjectName(_fromUtf8("checkBox_addToLib"))
        self.layout_advancedSettings.addWidget(self.checkBox_addToLib, 1, 1, 1, 1)
        self.label_addToLib = QtGui.QLabel(self.AdvancedSettings)
        self.label_addToLib.setObjectName(_fromUtf8("label_addToLib"))
        self.layout_advancedSettings.addWidget(self.label_addToLib, 1, 0, 1, 1)
        self.label_tolGIE = QtGui.QLabel(self.AdvancedSettings)
        self.label_tolGIE.setObjectName(_fromUtf8("label_tolGIE"))
        self.layout_advancedSettings.addWidget(self.label_tolGIE, 3, 0, 1, 1)
        self.lineEdit_tolGIE = QtGui.QLineEdit(self.AdvancedSettings)
        self.lineEdit_tolGIE.setText(_fromUtf8(""))
        self.lineEdit_tolGIE.setObjectName(_fromUtf8("lineEdit_tolGIE"))
        self.layout_advancedSettings.addWidget(self.lineEdit_tolGIE, 3, 1, 1, 1)
        self.label_tolModes = QtGui.QLabel(self.AdvancedSettings)
        self.label_tolModes.setObjectName(_fromUtf8("label_tolModes"))
        self.layout_advancedSettings.addWidget(self.label_tolModes, 4, 0, 1, 1)
        self.label_numberCPU = QtGui.QLabel(self.AdvancedSettings)
        self.label_numberCPU.setObjectName(_fromUtf8("label_numberCPU"))
        self.layout_advancedSettings.addWidget(self.label_numberCPU, 2, 0, 1, 1)
        self.spinBox_numberCPU = QtGui.QSpinBox(self.AdvancedSettings)
        self.spinBox_numberCPU.setMinimum(1)
        self.spinBox_numberCPU.setProperty("value", 4)
        self.spinBox_numberCPU.setObjectName(_fromUtf8("spinBox_numberCPU"))
        self.layout_advancedSettings.addWidget(self.spinBox_numberCPU, 2, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.layout_advancedSettings)
        self.form.addTab(self.AdvancedSettings, _fromUtf8(""))
        self.ReductionSteps = QtGui.QWidget()
        self.ReductionSteps.setObjectName(_fromUtf8("ReductionSteps"))
        self.verticalLayout = QtGui.QVBoxLayout(self.ReductionSteps)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.layout_reductionSteps = QtGui.QVBoxLayout()
        self.layout_reductionSteps.setObjectName(_fromUtf8("layout_reductionSteps"))
        self.checkBox_executeAll = QtGui.QCheckBox(self.ReductionSteps)
        self.checkBox_executeAll.setObjectName(_fromUtf8("checkBox_executeAll"))
        self.layout_reductionSteps.addWidget(self.checkBox_executeAll)
        self.checkBox_phase1 = QtGui.QCheckBox(self.ReductionSteps)
        self.checkBox_phase1.setObjectName(_fromUtf8("checkBox_phase1"))
        self.layout_reductionSteps.addWidget(self.checkBox_phase1)
        self.checkBox_phase2 = QtGui.QCheckBox(self.ReductionSteps)
        self.checkBox_phase2.setObjectName(_fromUtf8("checkBox_phase2"))
        self.layout_reductionSteps.addWidget(self.checkBox_phase2)
        self.checkBox_phase3 = QtGui.QCheckBox(self.ReductionSteps)
        self.checkBox_phase3.setObjectName(_fromUtf8("checkBox_phase3"))
        self.layout_reductionSteps.addWidget(self.checkBox_phase3)
        self.checkBox_phase4 = QtGui.QCheckBox(self.ReductionSteps)
        self.checkBox_phase4.setObjectName(_fromUtf8("checkBox_phase4"))
        self.layout_reductionSteps.addWidget(self.checkBox_phase4)
        self.verticalLayout.addLayout(self.layout_reductionSteps)
        self.layout_launchReduction = QtGui.QGridLayout()
        self.layout_launchReduction.setObjectName(_fromUtf8("layout_launchReduction"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_launchReduction.addItem(spacerItem1, 0, 0, 1, 1)
        self.btn_launchReduction = QtGui.QPushButton(self.ReductionSteps)
        self.btn_launchReduction.setObjectName(_fromUtf8("btn_launchReduction"))
        self.layout_launchReduction.addWidget(self.btn_launchReduction, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.layout_launchReduction)
        self.layout_preExecutionInfos = QtGui.QVBoxLayout()
        self.layout_preExecutionInfos.setObjectName(_fromUtf8("layout_preExecutionInfos"))
        self.label_preExecutionInfos = QtGui.QLabel(self.ReductionSteps)
        self.label_preExecutionInfos.setObjectName(_fromUtf8("label_preExecutionInfos"))
        self.layout_preExecutionInfos.addWidget(self.label_preExecutionInfos)
        self.textEdit_preExecutionInfos = QtGui.QTextEdit(self.ReductionSteps)
        self.textEdit_preExecutionInfos.setReadOnly(True)
        self.textEdit_preExecutionInfos.setObjectName(_fromUtf8("textEdit_preExecutionInfos"))
        self.layout_preExecutionInfos.addWidget(self.textEdit_preExecutionInfos)
        self.verticalLayout.addLayout(self.layout_preExecutionInfos)
        self.form.addTab(self.ReductionSteps, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.form)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 762, 19))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionAbout_ModelOrderReduction = QtGui.QAction(MainWindow)
        self.actionAbout_ModelOrderReduction.setObjectName(_fromUtf8("actionAbout_ModelOrderReduction"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionReset = QtGui.QAction(MainWindow)
        self.actionReset.setObjectName(_fromUtf8("actionReset"))
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionReset)
        self.menuHelp.addAction(self.actionAbout_ModelOrderReduction)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.form.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_path.setText(_translate("MainWindow", "Path", None))
        self.btn_scene.setText(_translate("MainWindow", "Scene", None))
        self.btn_mesh.setText(_translate("MainWindow", "Mesh", None))
        self.btn_output.setText(_translate("MainWindow", "Output", None))
        self.label_reductionParam.setText(_translate("MainWindow", "Reduction Parameters", None))
        self.label_NodeToReduce.setToolTip(_translate("MainWindow", "paths to models to reduce", None))
        self.label_NodeToReduce.setText(_translate("MainWindow", "Node To Reduce", None))
        self.label_AddTranslation.setToolTip(_translate("MainWindow", "allow translation along [x,y,z] axis of our reduced model", None))
        self.label_AddTranslation.setText(_translate("MainWindow", "Add Translation", None))
        self.label_moduleName.setText(_translate("MainWindow", "Module Name", None))
        self.lanel_animationParam.setText(_translate("MainWindow", "Animation Parameters", None))
        item = self.tableWidget_animationParam.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "location", None))
        item = self.tableWidget_animationParam.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "animation function", None))
        item = self.tableWidget_animationParam.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "object name", None))
        item = self.tableWidget_animationParam.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "parameters", None))
        self.btn_addLine.setText(_translate("MainWindow", "Add", None))
        self.btn_removeLine.setText(_translate("MainWindow", "Remove", None))
        self.form.setTabText(self.form.indexOf(self.MainParameters), _translate("MainWindow", "1) Main Parameters", None))
        self.label_toKeep.setText(_translate("MainWindow", "To keep", None))
        self.label_verbose.setText(_translate("MainWindow", "Verbose", None))
        self.label_addToLib.setText(_translate("MainWindow", "Add to lib", None))
        self.label_tolGIE.setToolTip(_translate("MainWindow", "tolerance applied to calculated GIE", None))
        self.label_tolGIE.setText(_translate("MainWindow", "Tolerance GIE", None))
        self.label_tolModes.setToolTip(_translate("MainWindow", "tolerance applied to choose the modes", None))
        self.label_tolModes.setText(_translate("MainWindow", "Tolerance Modes", None))
        self.label_numberCPU.setText(_translate("MainWindow", "Number of CPU", None))
        self.form.setTabText(self.form.indexOf(self.AdvancedSettings), _translate("MainWindow", "2) Advanced Settings", None))
        self.checkBox_executeAll.setText(_translate("MainWindow", "Execute All", None))
        self.checkBox_phase1.setText(_translate("MainWindow", "Phase 1", None))
        self.checkBox_phase2.setText(_translate("MainWindow", "Phase 2 ", None))
        self.checkBox_phase3.setText(_translate("MainWindow", "Phase 3", None))
        self.checkBox_phase4.setText(_translate("MainWindow", "Phase 4", None))
        self.btn_launchReduction.setText(_translate("MainWindow", "Launch Reduction", None))
        self.label_preExecutionInfos.setText(_translate("MainWindow", "Pre - Execution Infos", None))
        self.form.setTabText(self.form.indexOf(self.ReductionSteps), _translate("MainWindow", "3) Reduction Steps", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionAbout_ModelOrderReduction.setText(_translate("MainWindow", "About ModelOrderReduction", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as...", None))
        self.actionReset.setText(_translate("MainWindow", "Reset", None))
        self.actionReset.setShortcut(_translate("MainWindow", "Ctrl+R", None))

